### ISSUE TITLE
marker移动到屏幕上方的边缘时突然消失

### ISSUE THREAD

**Issue by maoxiao** [amap-demo/android-cluster-marker#2]
你好，我想问一下为什么当移动地图使maker移近屏幕边缘（maker大约出屏幕1/2时突然消失）时会突然消失？我自己开发的app也有这个问题。有什么解决方案么？

![screenshot_2017-01-22-19-23-32-378_com amap apis cluster](https://cloud.githubusercontent.com/assets/2288646/22182158/1a84cf08-e0d9-11e6-8dc7-12c1dee44c8f.png)

**Comment by qiyy** [comment]
问题是这样的，聚合的时候，为了计算效率 有一步是计算点在不在屏幕内 现在marker的锚点设置的是0.5 0.5 所以图片出屏幕一半时候就不算内部了 所以没参与计算。如果对聚合时候这个效果有要求的话，可以考虑将获取屏幕的bounds外扩一点，屏幕外一部分数据也可以参与到计算了。如果不是聚合的效果 单纯是marker显示的话 SDK本身已经做了判断 整个图片不在范围内 才做一些优化处理

**Comment by maoxiao** [comment]
@qiyy  对，我是指单纯marker。这个demo只有marker接近屏幕顶部是maker才会突然消失，而左右下都没有影响。我发现美团app地图（高德地图）也有类似问题，只不过是左和右边缘会触发。而我自己的app问题更多，我把mapview放在framelayout里，在地图当上方有一层透明的title bar（屏幕顶部），当marker刚刚触及tittle bar时（不是一半重叠）就消失了，而屏幕底部的透明bottom bar却不受影响。另外，我是用BitmapDescriptorFactory.fromView来为marker创建icon。是不是sdk的优化有点小问题，有没有什么好的解决方案

**Comment by qiyy** [comment]
好，我反馈下，看看有没有这个问题，另外相关问题和疑问 你可以反馈到我们的工单系统  有相关同学会为你解答

**Comment by qiyy** [comment]
我看了下demo 应该没这个问题 有点怀疑是不是跟你上边的那个bar有什么问题，有问题直接提工单吧

**Comment by maoxiao** [comment]
@qiyy  好的，谢谢了
