### ISSUE TITLE
聚合点不会分裂向下分裂

### ISSUE THREAD

**Issue by LZHIQI** [amap-demo/android-cluster-marker#3]
我这边遇到个问题，就是说几个经纬度点相差4米以下的情况下，距个点不会分裂，请问能给个思路么

**Comment by qiyy** [comment]
可以根据实际需求 调整示例中clusterRadius的值试一下。在ClusterOverlay构造函数中已经提供了聚合范围大小的参数设置入口
/**
     * 构造函数
     *
     * @param amap
     * @param clusterSize 聚合范围的大小（指点像素单位距离内的点会聚合到一个点显示）
     * @param context
     */
    public ClusterOverlay(AMap amap, int clusterSize, Context context) {
        this(amap, null, clusterSize, context);


    }

**Comment by HiDuke** [comment]
怎么判断地图上目前显示的有单个的marker
