### ISSUE TITLE
怎么监听判断手机屏幕显示的区域 地图上目前是否有单个的marker

### ISSUE THREAD

**Issue by HiDuke** [amap-demo/android-cluster-marker#4]
怎么监听判断手机屏幕显示的区域 地图上目前是否有单个的marker  我要对这些单独显示出来的marker搞事情

**Comment by qiyy** [comment]
有个变通的做法，clusteroverlay 有个addSingleClusterToMap 这个方法，在这里边可以拿到每一个聚合点，如果cluster.getClusterCount方法获取结果为1就是单独的，然后就可以拿他搞事情了，不过不知道你的需求大体是什么样的 ，我可以看下 是不是可以在原来基础上扩展下功能

**Comment by HiDuke** [comment]
我的需求是在单个marker的时候不显示marker  而是显示一个circle 已经搞定了 谢谢
