### ISSUE TITLE
假如多个marker样式，多个list item

### ISSUE THREAD

**Issue by Xiaocai9527** [amap-demo/android-cluster-marker#7]
我用这个ClusterOverlay，只保留了最后一个list。。
然后我写了5个ClusterOverlay，也不管用。。

**Comment by Xiaocai9527** [comment]
我把构造函数加了5个list，传进去几种。给cluster设置一个type，getBitmapDes方法中根据type来定样式。
但是只显示两个样式。。。

**Comment by qiyy** [comment]
5个ClusterOverlay 不管用的原因是只有一个ClusterOverlay能拿到地图视角移动的回调，这个你在源码基础上修改下应该可以实现；第二个不生效的 你调试下 或者加下日志看下  映射图标这块整体逻辑不是很复杂 你可以看下代码

**Comment by Moosphan** [comment]
我也遇到该问题,加入第三种标签时,前两种聚合标签的点击事件会被覆盖,请问如何改呢?

**Comment by qiyy** [comment]
amap.setOnMarkerClickListener(this); 这个生效只有一个，如果多个需要将这个事件传递到每一个里边，所以前边的被覆盖掉了，可以将这个事件统一拿出来处理 然后分发到每一个里

**Comment by Moosphan** [comment]
ok,谢谢

**Comment by qiyy** [comment]
或者可以提供下你具体的需求，我们可以考虑下改下这个示例，让他兼容的场景更多些

**Comment by Moosphan** [comment]
需求:1.地图上聚合商家和普通用户两种标签,点击不同类标签后处理不同的逻辑;
        2.marker图标的定制化,可以加载网络图片

**Comment by Moosphan** [comment]
这应该是时下最经常用到的两种需求了,如果高德能够改善,对于我们开发者也是福音了哈哈

**Comment by Xiaocai9527** [comment]
1.点击marker处理不同逻辑。这没什么吧，判断下不就行了吗。
2.加载网络图片。可以先把bitmap下载下来，再添加。

**Comment by Moosphan** [comment]
聚合点A和聚合点B两类,点击A后,B也会变成A的逻辑,问题不是很好描述,你自己试一下就知道了

**Comment by Xiaocai9527** [comment]
这问题是我提的。。。。你完全可以用两层聚合--数据不用加载一起。这样就行了

**Comment by Moosphan** [comment]
没听懂你说的什么意思

**Comment by qiyy** [comment]
@Moosphan   第一个需求 我们可以后续加入类型，根据类型进行聚合，第二个需求 可参考这个示例：
https://github.com/amap-demo/android-map-markerwebicon

**Comment by Moosphan** [comment]
好的

**Comment by Moosphan** [comment]
cluster本质还是marker,我将onMarkerClick集中处理后,多种聚合标签依旧会调onMarkerClick方法,还存在着聚合点和普通marker之间的点击事件冲突问题,有什么好的思路吗?我自己先写个marker点击监听器,传入类型参数试试行不行🙄

**Comment by Xiaocai9527** [comment]
根据聚合cluster的size来判断即可。

**Comment by Moosphan** [comment]
不不,走cluster点击事件之前会先走onMarkerClick

**Comment by Xiaocai9527** [comment]
是啊，你在onMarkerClick里面判断cluster不行吗？

**Comment by Moosphan** [comment]
怎么判断,里面拿不到cluster的信息呀

**Comment by Xiaocai9527** [comment]
marker.getObject()啊。你仔细看看代码吧。
Cluster cluster = (Cluster) marker.getObject();

**Comment by Moosphan** [comment]
那么第一个问题就算解决了😆

**Comment by Xiaocai9527** [comment]
是。好棒棒

**Comment by Moosphan** [comment]
一语惊醒梦中人,多谢老哥啦

**Comment by Xiaocai9527** [comment]
heng，我今年才18--比你老，不存在的！！！

**Comment by qiyy** [comment]
@xiaokun19931126   哈哈  少年英雄，不过id貌似暴露年龄了

**Comment by Moosphan** [comment]
哈哈,看来还是要多研究源码了
