### ISSUE TITLE
在地图缩放时候，怎么判断聚合的文字是哪个省或市，或区

### ISSUE THREAD

**Issue by wkfym** [amap-demo/android-cluster-marker#9]
在地图缩放时候，怎么判断聚合的文字上是显示哪个省，还是哪个市，还是哪个区？

**Comment by qiyy** [comment]
这个不是一个功能吧  说下你的原始需求吧

**Comment by awkfym1** [comment]
![image](https://user-images.githubusercontent.com/9802165/33977707-10490dfc-e0d7-11e7-9416-b53d9b578371.png)

**Comment by wkfym** [comment]
需求说明：在地图缩放的时候，  伸缩一点的时候  显示 对应的 全国的聚合点的数量， 
继续伸缩 或点击 全国聚合点的图标时候，显示各省的聚合点的数量；在继续伸缩 或 点击 某一个省聚合点的图标时候，显示 一个省的各市的聚合点的数量， 在继续伸缩 或 点击 某一个市聚合点的图标时候，显示 一个市 的各个地区的聚合点数量，  在继续伸缩 或  在点击地区的聚合点 的时候，显示 每一个点的坐标图。

**Comment by wkfym** [comment]
![wechatimg3](https://user-images.githubusercontent.com/9802165/33978322-1a8a6326-e0da-11e7-88f9-daad89a23c19.jpeg)

**Comment by wkfym** [comment]
类似这种效果，请问大哥这个怎么处理？有什么比较好的方案？

**Comment by qiyy** [comment]
可以在目前的基础上改，首先在聚合的时候可以根据不同分类进行聚合，其次设置一个级别，例如地图在0-4级以全国进行聚合，5级-8级 以省属性进行聚合，8-12之后以市属性聚合，15级之后不再进行聚合，只是思路 可能效果 根据实际情况进行调整

**Comment by wkfym** [comment]
看了你的思路：有几个疑问：

   1：我们从后台取数据问题：
      后台接口是只给我们latitude；longitude字段，
      还是给我们 latitude，longitude,省，市，区 5个字段都给；
      (如果后台 只给我们latitude；longitude字段,那么 聚合上的文字：各省，各市，各区的名字 是从哪里获取的，不会是根据经纬度 在去查找吧？)
      还是这种json格式（数组套数组的形式）：
   {
"全国" :
{
    "浙江省" :
[ 
  杭州市：{
 [
    {
        下城区：{
        }
    }
    ]
  }
]
}
}

  2：你说的根据级别聚合：  你说的根据级别指的是： 地图比例尺 还是 地图的缩放级别？
  3： 不太明白 你说的----  ”首先在聚合的时候可以根据不同分类进行聚合“这句话的意思。
     这个不同分类指的是什么？是指 后台 返回的字段标识吗？
      是不是 后台给数据：返回的Json数据格式： 要 数组 嵌套 数组(嵌套几层数组)的形式 返回给我们数据，然后我们根据每一层 数组数据 进行不同分类 进行聚合？

       是不是这个意思？

**Comment by qiyy** [comment]
1:后台数据给的是类似json形式，能拿到经纬度，也可以拿到省市区的属性数据
2:地图缩放级别，比例尺都可以，说白了就在地图缩放到什么状态以省的方式聚合，什么级别按市级别聚合更合适
3:目前的聚合方法只考虑了距离进行聚合，而你们实际需求还要参考他的属性信息（行政区划），按目前的聚合方法，比方说北京跟河北交界的地方可能就聚到一起了，而你们的需求是 北京的要聚合到北京去，河北到聚合到河北去

**Comment by wkfym** [comment]
好的，多谢大哥的帮忙，你的思路我明白了。
